# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import random as rd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 428)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("{\"font-colour=red;\"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.next_number = QtWidgets.QPushButton(self.centralwidget)
        self.next_number.setGeometry(QtCore.QRect(380, 280, 101, 31))
        self.next_number.setObjectName("next_number")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(240, 280, 101, 31))
        self.close.setObjectName("close")
        self.house1 = QtWidgets.QCheckBox(self.centralwidget)
        self.house1.setGeometry(QtCore.QRect(30, 200, 71, 21))
        self.house1.setChecked(False)
        self.house1.setObjectName("house1")
        self.upperlabel = QtWidgets.QLabel(self.centralwidget)
        self.upperlabel.setGeometry(QtCore.QRect(190, 0, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.upperlabel.setFont(font)
        self.upperlabel.setMouseTracking(False)
        self.upperlabel.setTextFormat(QtCore.Qt.AutoText)
        self.upperlabel.setScaledContents(False)
        self.upperlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.upperlabel.setObjectName("upperlabel")
        self.previuos_number = QtWidgets.QLabel(self.centralwidget)
        self.previuos_number.setGeometry(QtCore.QRect(300, 140, 91, 16))
        self.previuos_number.setObjectName("previuos_number")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 120, 120, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line1 = QtWidgets.QCheckBox(self.frame)
        self.line1.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QCheckBox(self.frame)
        self.line2.setGeometry(QtCore.QRect(20, 160, 70, 17))
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QCheckBox(self.frame)
        self.line3.setGeometry(QtCore.QRect(20, 180, 70, 17))
        self.line3.setObjectName("line3")
        self.house2 = QtWidgets.QCheckBox(self.frame)
        self.house2.setGeometry(QtCore.QRect(20, 100, 70, 17))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.house2.setFont(font)
        self.house2.setObjectName("house2")
        self.corners = QtWidgets.QCheckBox(self.frame)
        self.corners.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.corners.setObjectName("corners")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 220, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 240, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.mdiArea = QtWidgets.QMdiArea(self.frame)
        self.mdiArea.setGeometry(QtCore.QRect(10, 50, 91, 211))
        self.mdiArea.setObjectName("mdiArea")
        self.mdiArea.raise_()
        self.checkBox.raise_()
        self.house2.raise_()
        self.corners.raise_()
        self.label.raise_()
        self.line2.raise_()
        self.line3.raise_()
        self.line1.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(260, 70, 181, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 50, 47, 14))
        self.label_2.setObjectName("label_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(260, 160, 181, 61))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.frame.raise_()
        self.next_number.raise_()
        self.close.raise_()
        self.house1.raise_()
        self.upperlabel.raise_()
        self.previuos_number.raise_()
        self.lcdNumber.raise_()
        self.label_2.raise_()
        self.lcdNumber_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.close.clicked.connect(MainWindow.close)
        self.next_number.clicked.connect(self.numbers)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    global l,e
    
    e=[0]
    l=[i for i in range(1,91) ]
    def numbers(self):
        x=rd.choice(l)
        l.remove(x)
        self.lcdNumber.display(x)
        e.append(x)
        y=e[0]
        e.remove(y)
        self.lcdNumber_2.display(y)
        #time.sleep(10)
        if len(l)==0:
            print("all numbers finished")
    
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_number.setText(_translate("MainWindow", "Next Number"))
        self.close.setText(_translate("MainWindow", "Close"))
        self.house1.setText(_translate("MainWindow", "1st HOUSE"))
        self.upperlabel.setText(_translate("MainWindow", "HOUSE se HOUSIE"))
        self.previuos_number.setText(_translate("MainWindow", "Previous Number"))
        self.label.setText(_translate("MainWindow", "PRIZES"))
        self.line1.setText(_translate("MainWindow", "1st Line"))
        self.line2.setText(_translate("MainWindow", "2nd Line"))
        self.line3.setText(_translate("MainWindow", "3rd LINE"))
        self.house2.setText(_translate("MainWindow", "2nd house"))
        self.corners.setText(_translate("MainWindow", "Corners"))
        self.checkBox.setText(_translate("MainWindow", "BP"))
        self.checkBox_2.setText(_translate("MainWindow", "budhapa"))
        self.checkBox_3.setText(_translate("MainWindow", "jawani"))
        self.label_2.setText(_translate("MainWindow", "Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
